const express = require('express');
require('dotenv').config({ path: './.env' });
// const { engine } = require('express-handlebars');
// const fs = require('fs');

// Optional remove the hashes generated by Vite
// const files = fs.readdirSync('./dist/js/');
// files.forEach((file) => {
//     const hashless = file.replace(/\.[a-zA-Z0-9]*\.js/g, '.js');
//     fs.rename(`./dist/js/${file}`, `./dist/js/${hashless}`, function (err) {
//         if (err) throw new Error('Failed to remove hashes');
//     });
// });

const app = express();
const PORT = process.env.PORT || 3000;

// Set up handlebars so that eventually it will render server side on production also
// app.engine('html', engine({ defaultLayout: false }));
// app.set('view engine', 'html');
// app.set('views', './dist');

app.use(express.static('./dist'));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

app.listen(PORT, () => console.log(`Started listening on port ${PORT}`));

module.exports = app;
